### PR TITLE
Feature/pchakrab/#3 create mapz driver

### PR DESCRIPTION
**Pull request by pchakraborty**
This is a working version of the mapz driver

### CODE REVIEW

**Comment by mathomp4** [comment]
@pchakraborty I added the needed labels to pass the check.

**Comment by mathomp4** [comment]
Also, I suppose technically this should be to `geos/develop` but I don't know... I did my PR against it, but @tclune might know more.

**Comment by pchakraborty** [comment]
@mathomp4 That makes sense. I edited the base branch of the PR (geos/master -> geos/develop)

**Review by tclune — COMMENTED** [review]
(1) It looks like some of this is a direct copy.  Is that wise?
(2) I suspect the home for this needs to move.  But that is easy enough in Git later on.

**Comment by pchakraborty** [comment]
> (1) It looks like some of this is a direct copy. Is that wise?

Parts of external_ic.F90 and fv_grid_utils.F90 are copied to external_ic_stub.F90 and fv_grid_utils_stub.f90 purely to limit the number dependencies to a manageable level.

**Review by tclune — APPROVED** [review]

**Pull request merged**
